version: '3'

services:
  web: &app_base
    build:
      context: .
      dockerfile: Dockerfile_div
    ports:
      - "3000:3000"
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root@mysql:3306 #これ超重！要絶対パスで場所を指定ってことなのかな？
      # MYSQL_ROOT_PASSWORD: root
    volumes:
      - .:/myapp
    depends_on:
      - mysql
      - chrome
      - webpack

  webpack:
    build:
      context: .
      dockerfile: Dockerfile_div
    command: "yarn build"    
    command: "yarn start"
    ports:
      - "3035:3035"
    # depends_on:
      # - web
    tty: false
    stdin_open: false

  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_PASSWORD: root 
      MYSQL_DATABASE: myapp_development
      # MYSQL_DATABASE: myapp_test
      MYSQL_USERNAME: root
    ports:
    - 4306:3306
    volumes:
      -  ./mysql_data:/var/lib/mysql

  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
        
volumes:
  bundle:
  mysql_data: