version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root@mysql:3306 #これ超重！要絶対パスで場所を指定ってことなのかな？
      # MYSQL_ROOT_PASSWORD: root
    volumes:
      - .:/myapp
    depends_on:
      - mysql
      - chrome
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_PASSWORD: root 
      MYSQL_DATABASE: myapp_development
      MYSQL_USERNAME: root

    ports:
    - 4306:3306
    volumes:
      -  ./mysql_data:/var/lib/mysql
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
        
volumes:
  bundle:
  mysql_data: