version: '3'

services:

  web: 
    build:
      context: .
      dockerfile: Dockerfile_div
    ports:
      - "3000:3000" #rails
      - "3035:3035" #webpack
    tty: true
    stdin_open: true
    command: foreman start
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root@mysql:3306
    volumes:
      - .:/myapp
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp_development
      MYSQL_USERNAME: root
    ports:
    - 4306:3306
    volumes:
      -  ./mysql_data:/var/lib/mysql

volumes:
  bundle:
  mysql_data: